FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN yarn install

COPY tailwind.config.js tailwind.config.js ./
COPY tsconfig.json tsconfig.json ./

COPY src ./src
COPY public ./public

CMD ["yarn","start"]